pyuic5 -o ui_about.py About.ui
pyuic5 -o ui_arcNote.py AddArcNote.ui
pyuic5 -o ui_arcTap.py AddArcTap.ui
pyuic5 -o ui_longNote.py AddLongNote.ui
pyuic5 -o ui_tapNote.py AddTapNote.ui
pyuic5 -o ui_timing.py AddTiming.ui
pyuic5 -o ui_delArcTap.py DelArcTap.ui
pyuic5 -o ui_downloadProgress.py DownloadProgress.ui
pyuic5 -o ui_newScore.py newScore.ui
pyuic5 -o ui_main.py qtArcaea.ui
pyuic5 -o ui_quesArcTap.py QuesArcTAp.ui