# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddArcNote.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddArcNote(object):
    def setupUi(self, AddArcNote):
        AddArcNote.setObjectName("AddArcNote")
        AddArcNote.resize(366, 509)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddArcNote.sizePolicy().hasHeightForWidth())
        AddArcNote.setSizePolicy(sizePolicy)
        AddArcNote.setMinimumSize(QtCore.QSize(366, 509))
        AddArcNote.setMaximumSize(QtCore.QSize(366, 509))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/arcaea_main/res/ase-256x256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/arcaea_main/res/ase-256x256.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        AddArcNote.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(AddArcNote)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(AddArcNote)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Y_end_label = QtWidgets.QLabel(AddArcNote)
        self.Y_end_label.setObjectName("Y_end_label")
        self.gridLayout_2.addWidget(self.Y_end_label, 0, 1, 1, 1)
        self.Y_end = QtWidgets.QSpinBox(AddArcNote)
        self.Y_end.setMaximum(999999)
        self.Y_end.setObjectName("Y_end")
        self.gridLayout_2.addWidget(self.Y_end, 1, 1, 1, 1)
        self.Y_start = QtWidgets.QSpinBox(AddArcNote)
        self.Y_start.setMaximum(999999)
        self.Y_start.setObjectName("Y_start")
        self.gridLayout_2.addWidget(self.Y_start, 1, 0, 1, 1)
        self.Y_start_label = QtWidgets.QLabel(AddArcNote)
        self.Y_start_label.setObjectName("Y_start_label")
        self.gridLayout_2.addWidget(self.Y_start_label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label = QtWidgets.QLabel(AddArcNote)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.X_start_label = QtWidgets.QLabel(AddArcNote)
        self.X_start_label.setObjectName("X_start_label")
        self.gridLayout_3.addWidget(self.X_start_label, 0, 0, 1, 1)
        self.X_end_label = QtWidgets.QLabel(AddArcNote)
        self.X_end_label.setObjectName("X_end_label")
        self.gridLayout_3.addWidget(self.X_end_label, 0, 1, 1, 1)
        self.X_start = QtWidgets.QDoubleSpinBox(AddArcNote)
        self.X_start.setMinimum(-1.5)
        self.X_start.setMaximum(1.5)
        self.X_start.setSingleStep(0.1)
        self.X_start.setObjectName("X_start")
        self.gridLayout_3.addWidget(self.X_start, 1, 0, 1, 1)
        self.X_end = QtWidgets.QDoubleSpinBox(AddArcNote)
        self.X_end.setMinimum(-1.5)
        self.X_end.setMaximum(1.5)
        self.X_end.setSingleStep(0.1)
        self.X_end.setObjectName("X_end")
        self.gridLayout_3.addWidget(self.X_end, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.label_3 = QtWidgets.QLabel(AddArcNote)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.Z_end = QtWidgets.QDoubleSpinBox(AddArcNote)
        self.Z_end.setMaximum(1.0)
        self.Z_end.setSingleStep(0.1)
        self.Z_end.setObjectName("Z_end")
        self.gridLayout_4.addWidget(self.Z_end, 1, 1, 1, 1)
        self.Z_start_label = QtWidgets.QLabel(AddArcNote)
        self.Z_start_label.setObjectName("Z_start_label")
        self.gridLayout_4.addWidget(self.Z_start_label, 0, 0, 1, 1)
        self.Z_end_label = QtWidgets.QLabel(AddArcNote)
        self.Z_end_label.setObjectName("Z_end_label")
        self.gridLayout_4.addWidget(self.Z_end_label, 0, 1, 1, 1)
        self.Z_start = QtWidgets.QDoubleSpinBox(AddArcNote)
        self.Z_start.setMaximum(1.0)
        self.Z_start.setSingleStep(0.1)
        self.Z_start.setObjectName("Z_start")
        self.gridLayout_4.addWidget(self.Z_start, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.label_12 = QtWidgets.QLabel(AddArcNote)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.curve_label = QtWidgets.QLabel(AddArcNote)
        self.curve_label.setObjectName("curve_label")
        self.gridLayout_7.addWidget(self.curve_label, 0, 0, 1, 1)
        self.color_label = QtWidgets.QLabel(AddArcNote)
        self.color_label.setObjectName("color_label")
        self.gridLayout_7.addWidget(self.color_label, 0, 1, 1, 1)
        self.color = QtWidgets.QSpinBox(AddArcNote)
        self.color.setMaximum(1)
        self.color.setObjectName("color")
        self.gridLayout_7.addWidget(self.color, 1, 1, 1, 1)
        self.curve = QtWidgets.QLineEdit(AddArcNote)
        self.curve.setObjectName("curve")
        self.gridLayout_7.addWidget(self.curve, 1, 0, 1, 1)
        self.isTrace = QtWidgets.QCheckBox(AddArcNote)
        self.isTrace.setObjectName("isTrace")
        self.gridLayout_7.addWidget(self.isTrace, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.pushButton = QtWidgets.QPushButton(AddArcNote)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(AddArcNote)
        self.pushButton.clicked.connect(AddArcNote.new_note)
        QtCore.QMetaObject.connectSlotsByName(AddArcNote)

    def retranslateUi(self, AddArcNote):
        _translate = QtCore.QCoreApplication.translate
        AddArcNote.setWindowTitle(_translate("AddArcNote", "Add Arc Note"))
        self.label_2.setText(_translate("AddArcNote", "時間(ミリ秒)"))
        self.Y_end_label.setText(_translate("AddArcNote", "終了"))
        self.Y_start_label.setText(_translate("AddArcNote", "開始"))
        self.label.setText(_translate("AddArcNote", "位置(小数)[-1.5～1.5]"))
        self.X_start_label.setText(_translate("AddArcNote", "開始"))
        self.X_end_label.setText(_translate("AddArcNote", "終了"))
        self.label_3.setText(_translate("AddArcNote", "縦位置Z軸(小数)[0-1]"))
        self.Z_start_label.setText(_translate("AddArcNote", "開始"))
        self.Z_end_label.setText(_translate("AddArcNote", "終了"))
        self.label_12.setText(_translate("AddArcNote", "その他"))
        self.curve_label.setText(_translate("AddArcNote", "カーブタイプ(b, s, so, si のいずれか)"))
        self.color_label.setText(_translate("AddArcNote", "色(0 or 1)"))
        self.isTrace.setText(_translate("AddArcNote", "トレースノートにする"))
        self.pushButton.setText(_translate("AddArcNote", "追加"))

import main_rc
